# Generated by Django 3.0.3 on 2020-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50, verbose_name='アーティスト名')),
                ('lyricist', models.CharField(blank=True, max_length=50, null=True, verbose_name='作詞家')),
                ('composer', models.CharField(blank=True, max_length=50, null=True, verbose_name='作曲家')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='歌詞')),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
