# Generated by Django 3.0.3 on 2020-07-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mix_song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50, unique=True, verbose_name='アーティスト名')),
                ('page_index', models.IntegerField(max_length=2, verbose_name='ページ番号')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Artists',
            },
        ),
    ]
